baseURL = "/"
defaultContentLanguage = "zh-cn"

theme = "LoveIt"

enableRobotsTXT = true
enableGitInfo = true
enableEmoji = true

summaryLength = 150

[languages]
  [languages.zh-CN]
    weight = 1
    languageCode = "zh-cn"
    title = "未命名"
    languageName = "简体中文"
    hasCJKLanguage = true
    paginate = 12
    googleAnalytics = "UA-46567212-1"
    dateFormatToUse = "2006-01-02"

    [languages.zh-CN.menu]
      [[languages.zh-CN.menu.main]]
        identifier = "home"
        name = "主页"
        url = "/"
        weight = 1
      [[languages.zh-CN.menu.main]]
        identifier = "post"
        name = "技术"
        url = "/posts/"
        weight = 2
      [[languages.zh-CN.menu.main]]
        identifier = "life"
        name = "生活"
        url = "/life/"
        weight = 3
    [languages.zh-CN.params]
      description = ""
      keywords = ["tech","code"]
      # 网站默认主题 ("light", "dark", "auto")
      defaultTheme = "auto"
      # 主页信息设置
      [languages.zh-CN.params.home]
        # 主页个人信息
        [languages.zh-CN.params.home.profile]
          enable = true
          avatarURL = "/img/pic/avatar.jpg"
          subtitle = "成文的技术笔记会搬到这上面来～～编辑中..."
          typeit = true
          # 是否显示社交账号
          social = false
        # 主页文章列表
        [languages.zh-CN.params.home.posts]
          enable = true
          # 主页每页显示文章数量
          paginate = 6
          # 当你没有在文章前面设置 "hiddenFromHomePage" 时的默认行为
          defaultHiddenFromHomePage = false
      # 主页的社交信息设置
      [languages.zh-CN.params.social]
        GitHub = "xxxx"
      [languages.zh-CN.params.share]
        enable = false
      # 评论系统设置
      [languages.zh-CN.params.comment]
        enable = true
        [languages.zh-CN.params.comment.disqus]
          shortname = "mindytech"

[params]
  # LoveIt theme version
  # LoveIt 主题版本
  version = "0.1.X"
  gitRepo = "https://github.com/9ft/log"

  toc = true
  autoCollapseToc = false

  [params.header]
    desktopMode = "auto"
    mobileMode = "auto"

  [params.footer]
    since = 2017

  [params.page]
    lightgallery = false
    linkToMarkdown = false
  # mathematical formulas (KaTeX)
  # 数学公式 (KaTeX https://katex.org/)
  [params.math]
    enable = true
    # default block delimiter is $$ ... $$ and \\[ ... \\]
    # 默认块定界符是 $$ ... $$ 和 \\[ ... \\]
    blockLeftDelimiter = ""
    blockRightDelimiter = ""
    # default inline delimiter is $ ... $ and \\( ... \\)
    # 默认内联定界符是 $ ... $ 和 \\( ... \\)
    inlineLeftDelimiter = ""
    inlineRightDelimiter = ""
    # KaTeX extension copy_tex
    # KaTeX 插件 copy_tex
    copyTex = true
    # KaTeX extension mhchem
    # KaTeX 插件 mhchem
    mhchem = true
  # site verification code for Google/Bing/Yandex/Pinterest/Baidu
  # 网站验证代码，用于 Google/Bing/Yandex/Pinterest/Baidu
  [params.verification]
    google = ""
    bing = ""
    yandex = ""
    pinterest = ""
    baidu = ""
  # Publisher Info just for SEO
  # 出版者信息，仅用于 SEO
  [params.publisher]
    name = "xxxx"
    [params.publisher.logo]
      url = "logo.png"
      width = 127
      height = 40
  # Website Log Info just for SEO
  # 网站 Logo 信息，仅用于 SEO
  [params.logo]
    url = "logo.png"
    width = 127
    height = 40
  # Website Image Info just for SEO
  #  网站图标信息，仅用于 SEO
  [params.image]
    url = "cover.png"
    width = 800
    height = 600
  # CSS and JS Files CDN
  # CSS 和 JS 文件的 CDN 设置
  [params.cdn]
    # fontawesome-free@5.12.1 https://fontawesome.com/
    fontawesomeFreeCSS = ''
    # animate.css@3.7.2 https://github.com/daneden/animate.css
    animateCSS = ''
    # smooth-scroll@16.1.2 https://github.com/cferdinandi/smooth-scroll
    smoothScrollJS = ''
    # sharer@0.4.0 https://github.com/ellisonleao/sharer.js
    sharerJS = ''
    # lazysizes@5.2.0 https://github.com/aFarkas/lazysizes
    lazysizesJS = ''
    # lightgallery@1.1.3 lg-thumbnail@1.1.0 lg-zoom@1.1.0 https://github.com/sachinchoolur/lightgallery.js
    lightgalleryCSS = ''
    lightgalleryJS = ''
    lightgalleryThumbnailJS = ''
    lightgalleryZoomJS = ''
    # typeit@6.5.1 https://github.com/alexmacarthur/typeit
    typeitJS = ''
    # katex@0.11.1 https://github.com/KaTeX/KaTeX
    katexCSS = ''
    katexJS = ''
    katexAutoRenderJS = ''
    katexCopyTexCSS = ''
    katexCopyTexJS = ''
    katexMhchemJS = ''
    # mermaid@8.4.8 https://github.com/knsv/mermaid
    mermaidJS = ''
    # aplayer@1.10.1 https://github.com/MoePlayer/APlayer
    aplayerCSS = ''
    aplayerJS = ''
    # meting@2.0.1 https://github.com/metowolf/MetingJS
    metingJS = ''
    # echarts@4.6.0 https://echarts.apache.org/
    echartsJS = ''
    echartsMacaronsJS = ''
    # gitalk@1.6.0 https://github.com/gitalk/gitalk
    gitalkCSS = ''
    gitalkJS = ''
    # valine@1.3.10 https://valine.js.org/
    valineJS = ''

# Markup related configuration in Hugo
# Hugo 解析文档的配置
[markup]
  # Syntax Highlighting (https://gohugo.io/content-management/syntax-highlighting)
  # 代码高亮设置 (https://gohugo.io/content-management/syntax-highlighting)
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    lineNos = true
    lineNumbersInTable = true
    noClasses = false
    style = "monokai"
    tabWidth = 4
  # Goldmark is from Hugo 0.60 the default library used for Markdown
  # Goldmark 是 Hugo 0.60 以来的默认 Markdown 解析库
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.renderer]
      # whether to use HTML tags directly in the document
      # 是否在文档中直接使用 HTML 标签
      unsafe = true

  [markup.tableOfContents]
    startLevel = 1

[author]
  name = "Minzhang Cong"
#  link = ""

[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5

# Permalinks Info (https://gohugo.io/content-management/urls/#permalinks)
[Permalinks]
  # posts = ":year/:month/:filename"
  # posts = ":sections"

# Privacy Info (https://gohugo.io/about/hugo-and-gdpr/)
# 隐私信息设置 (https://gohugo.io/about/hugo-and-gdpr/)
[privacy]
  [privacy.googleAnalytics]
    anonymizeIP = true

  [privacy.youtube]
    privacyEnhanced = true

